/**
 * Builds the Ak&Ven logo files from two sources of truth:
 *   - brand/mark-path.json   the heart-ampersand mark (filled outline, vectorised and cleaned from the shop sign)
 *   - Jost Medium            the wide-tracked capitals AK and VEN, converted to outlines here so the
 *                            finished logo needs no font anywhere (web, print, signage, favicon)
 * Output: public/brand/*.svg (gold, ink, white) and src/brand/logo.generated.ts (used by the React <Logo>).
 * Run: npm run logo
 */
import opentype from "opentype.js";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const mark = JSON.parse(fs.readFileSync(path.join(root, "brand/mark-path.json"), "utf8"));
const fontBuffer = fs.readFileSync(path.join(root, "node_modules/@fontsource/jost/files/jost-latin-500-normal.woff"));
const font = opentype.parse(fontBuffer.buffer.slice(fontBuffer.byteOffset, fontBuffer.byteOffset + fontBuffer.byteLength));

const SIZE = 200;                                   // font size used for layout; everything is relative
const CAP = (font.tables.os2.sCapHeight / font.unitsPerEm) * SIZE;
const TRACK = 0.11;                                  // letter-spacing in em: wide, airy, premium
const GAP_LEFT = 0.46 * CAP, GAP_RIGHT = 0.40 * CAP; // breathing room around the mark
const MARK_H = 1.72 * CAP;                           // the mark rises above the capitals like the shop sign
const MARK_DROP = 0.10 * CAP;                        // and dips slightly below the baseline

function glyphs(text, x) {
  const p = font.getPath(text, x, 0, SIZE, { letterSpacing: TRACK, kerning: true });
  const bb = p.getBoundingBox();
  return { path: p, x1: bb.x1, x2: bb.x2 };
}

const ak = glyphs("AK", 0);
const markScale = MARK_H / mark.h;
const markW = mark.w * markScale;
const markX = ak.x2 + GAP_LEFT;
const ven = glyphs("VEN", markX + markW + GAP_RIGHT);
const markY = MARK_DROP - MARK_H;                    // top of mark (y grows downward; baseline is y = 0)

const letterD = ak.path.toPathData(1) + " " + ven.path.toPathData(1);
const markD = mark.d;                                // in its own units, placed with a transform
const markTransform = `translate(${markX.toFixed(1)} ${markY.toFixed(1)}) scale(${markScale.toFixed(5)})`;

const pad = 0;
const minX = ak.x1 - pad, maxX = ven.x2 + pad;
const minY = markY - pad, maxY = MARK_DROP + pad;
const vbW = +(maxX - minX).toFixed(1), vbH = +(maxY - minY).toFixed(1);
const viewBox = `${minX.toFixed(1)} ${minY.toFixed(1)} ${vbW} ${vbH}`;

const GOLD = "#C9A24B", INK = "#16130F", WHITE = "#FFFFFF";
const svg = (fill, defs = "") => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="Ak&amp;Ven">${defs}<g fill="${fill}" fill-rule="evenodd"><path d="${letterD}"/><path transform="${markTransform}" d="${markD}"/></g></svg>\n`;
const markSvg = (fill, defs = "") => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${mark.w} ${mark.h}" role="img" aria-label="Ak&amp;Ven mark">${defs}<path fill="${fill}" fill-rule="evenodd" d="${markD}"/></svg>\n`;
const gradient = `<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#EBD596"/><stop offset=".5" stop-color="#C9A24B"/><stop offset="1" stop-color="#9C7A2D"/></linearGradient></defs>`;

const out = path.join(root, "public/brand");
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, "logo-gold.svg"), svg(GOLD));
fs.writeFileSync(path.join(out, "logo-gold-metallic.svg"), svg("url(#g)", gradient));
fs.writeFileSync(path.join(out, "logo-ink.svg"), svg(INK));
fs.writeFileSync(path.join(out, "logo-white.svg"), svg(WHITE));
fs.writeFileSync(path.join(out, "mark-gold.svg"), markSvg(GOLD));
fs.writeFileSync(path.join(out, "mark-gold-metallic.svg"), markSvg("url(#g)", gradient));
fs.writeFileSync(path.join(out, "mark-ink.svg"), markSvg(INK));
fs.writeFileSync(path.join(out, "mark-white.svg"), markSvg(WHITE));

fs.writeFileSync(path.join(root, "src/brand/logo.generated.ts"),
`// GENERATED by scripts/generate-logo.mjs. Do not edit by hand; run \`npm run logo\`.
export const LOGO = {
  viewBox: ${JSON.stringify(viewBox)},
  aspect: ${(vbW / vbH).toFixed(4)},
  letters: ${JSON.stringify(letterD)},
  markTransform: ${JSON.stringify(markTransform)},
  mark: ${JSON.stringify(markD)},
  markSize: { w: ${mark.w}, h: ${mark.h} },
} as const;
`);
console.log("logo", viewBox, "aspect", (vbW / vbH).toFixed(3));
